### ISSUE TITLE
Need for an Example App

### ISSUE THREAD

**Issue by papakay** [Cantido/liberator#40]
Nice work done so far.

I believe it will help a lot of those who want to try this out if there's an example app (may be a Todo or something) that shows proper usage of this library.

Thank you.

**Comment by Cantido** [comment]
Thank you! I totally agree. That's been the next thing on my to-do list for this app, I just haven't gotten around to it yet.

**Comment by Cantido** [comment]
I made a basic example project based on a generated Phoenix controller, here: https://github.com/Cantido/liberator_example.
At [`lib/liberator_example_web/controllers/post_controller.ex`](https://github.com/Cantido/liberator_example/blob/main/lib/liberator_example_web/controllers/post_controller.ex), you will find a Liberator resource that passes all of the controller tests generated using `mix phx.new.context`. Feel free to create another issue if you need anything else :)
